language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
before_install:
  - cd ruby && make deps
script:
  - cd ruby && SWAGGER_CODEGEN_JAR=../bin/swagger-codegen-cli-20160701.jar make clean build install doc
