language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
before_install:
  - cd ruby && make deps && cd ..
script:
  - cd ruby && SWAGGER_CODEGEN_JAR=../bin/swagger-codegen-cli-20160728.jar make clean build install doc  && cd ..
