swagger: '2.0'
info:
  title: Adobe Experience Manager (AEM) API
  description: An unofficial Adobe Experience Manager (AEM) API specification by Shine Solutions
  version: "6.2"
schemes:
  - http
  - https
basePath: /
produces:
  - text/html
  - text/plain
  - application/json
securityDefinitions:
  aemAuth:
    type: basic
security:
  - aemAuth: []
paths:
  /{path}/:
    post:
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: jcr:primaryType
          in: query
          required: true
          type: string
        - name: :name
          in: query
          required: true
          type: string
      tags:
        - sling
  /{path}/{name}:
    get:
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
    delete:
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
  /apps/system/config.{runmode}/{name}:
    post:
      parameters:
        - name: runmode
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: org.apache.felix.https.nio
          in: query
          required: false
          type: boolean
        - name: org.apache.felix.https.nio@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.clientcertificate
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.clientcertificate@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.enable
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.enable@TypeHint
          in: query
          required: false
          type: string
        - name: org.osgi.service.http.port.secure
          in: query
          required: false
          type: string
        - name: org.osgi.service.http.port.secure@TypeHint
          in: query
          required: false
          type: string
      tags:
        - sling
  /etc/replication/treeactivation.html:
    post:
      parameters:
        - name: ignoredeactivated
          in: query
          required: true
          type: boolean
        - name: onlymodified
          in: query
          required: true
          type: boolean
        - name: path
          in: query
          required: true
          type: string
      tags:
        - sling
  /system/console/bundles/{name}:
    post:
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: action
          in: query
          required: true
          type: string
      tags:
        - console
  /system/console/jmx/com.adobe.granite:type=Repository/op/{action}:
    post:
      parameters:
        - name: action
          in: path
          required: true
          type: string
      tags:
        - console
