swagger: '2.0'
info:
  title: Adobe Experience Manager (AEM) API
  description: An unofficial Adobe Experience Manager (AEM) API specification by Shine Solutions
  version: "6.2"
schemes:
  - http
  - https
basePath: /
produces:
  - text/html
  - text/plain
  - application/json
securityDefinitions:
  aemAuth:
    type: basic
security:
  - aemAuth: []
paths:
  .cqactions.html:
    post:
      operationId: postCqActions
      parameters:
        - name: authorizableId
          in: query
          required: true
          type: string
        - name: changelog
          in: query
          required: true
          type: string
      tags:
        - cq
  /{path}/:
    post:
      operationId: postPath
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: jcr:primaryType
          in: query
          required: true
          type: string
        - name: :name
          in: query
          required: true
          type: string
      tags:
        - sling
  /{path}/{name}:
    get:
      operationId: getNode
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
    delete:
      operationId: deleteNode
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
  /{path}/{name}.rw.html:
    post:
      operationId: postNodeRw
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: addMembers
          in: query
          required: false
          type: string
      tags:
        - sling
  /apps/system/config.{runmode}/{name}:
    post:
      operationId: postConfig
      parameters:
        - name: runmode
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: org.apache.felix.https.nio
          in: query
          required: false
          type: boolean
        - name: org.apache.felix.https.nio@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.keystore.key.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore.password
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.truststore.password@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.clientcertificate
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.clientcertificate@TypeHint
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.enable
          in: query
          required: false
          type: string
        - name: org.apache.felix.https.enable@TypeHint
          in: query
          required: false
          type: string
        - name: org.osgi.service.http.port.secure
          in: query
          required: false
          type: string
        - name: org.osgi.service.http.port.secure@TypeHint
          in: query
          required: false
          type: string
      tags:
        - sling
  /bin/querybuilder.json:
    post:
      operationId: postQuery
      parameters:
        - name: path
          in: query
          required: true
          type: string
        - name: p.limit
          in: query
          required: true
          type: number
        - name: 1_property
          in: query
          required: true
          type: string
        - name: 1_property.value
          in: query
          required: true
          type: string
      responses:
        default:
          schema:
            type: string
      tags:
        - sling
  /etc/packages/{group}/{name}-{version}.zip:
    get:
      operationId: getPackage
      parameters:
        - name: group
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: path
          required: true
          type: string
      responses:
        default:
          schema:
            type: file
      tags:
        - sling
  /etc/packages/{group}/{name}-{version}.zip/jcr:content/vlt:definition/filter.tidy.2.json:
    get:
      operationId: getPackageFilter
      parameters:
        - name: group
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: path
          required: true
          type: string
      responses:
        default:
          schema:
            type: string
      tags:
        - sling
  /etc/replication/agents.{runmode}/{name}:
    get:
      operationId: getAgent
      parameters:
        - name: runmode
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
    delete:
      operationId: deleteAgent
      parameters:
        - name: runmode
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - sling
    post:
      operationId: postAgent
      parameters:
        - name: runmode
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: jcr:primaryType
          in: query
          required: false
          type: string
        - name: jcr:content/cq:name
          in: query
          required: false
          type: string
        - name: jcr:content/jcr:title
          in: query
          required: false
          type: string
        - name: jcr:content/jcr:description
          in: query
          required: false
          type: string
        - name: jcr:content/sling:resourceType
          in: query
          required: false
          type: string
        - name: jcr:content/transportUri
          in: query
          required: false
          type: string
        - name: jcr:content/logLevel
          in: query
          required: false
          type: string
        - name: jcr:content/noVersioning
          in: query
          required: false
          type: boolean
        - name: jcr:content/protocolHTTPHeaders
          in: query
          required: false
          type: array
          collectionFormat: multi
        - name: jcr:content/protocolHTTPHeaders@TypeHint
          in: query
          required: false
          type: string
        - name: jcr:content/protocolHTTPMethod
          in: query
          required: false
          type: string
        - name: jcr:content/retryDelay
          in: query
          required: false
          type: string
        - name: jcr:content/serializationType
          in: query
          required: false
          type: string
        - name: jcr:content/jcr:mixinTypes
          in: query
          required: false
          type: string
        - name: jcr:content/triggerReceive
          in: query
          required: false
          type: boolean
        - name: jcr:content/triggerSpecific
          in: query
          required: false
          type: boolean
        - name: jcr:content/cq:template
          in: query
          required: false
          type: string
        - name: jcr:content/enabled
          in: query
          required: false
          type: boolean
      tags:
        - sling
  /etc/replication/treeactivation.html:
    post:
      operationId: postTreeActivation
      parameters:
        - name: ignoredeactivated
          in: query
          required: true
          type: boolean
        - name: onlymodified
          in: query
          required: true
          type: boolean
        - name: path
          in: query
          required: true
          type: string
      tags:
        - sling
  /libs/granite/security/post/authorizables:
    post:
      operationId: postAuthorizables
      parameters:
        - name: authorizableId
          in: query
          required: true
          type: string
        - name: intermediatePath
          in: query
          required: true
          type: string
        - name: createUser
          in: query
          required: false
          type: string
        - name: createGroup
          in: query
          required: false
          type: string
        - name: rep:password
          in: query
          required: false
          type: string
        - name: profile/givenName
          in: query
          required: false
          type: string
      tags:
        - sling
  /crx/explorer/ui/setpassword.jsp:
    post:
      operationId: postSetPassword
      parameters:
        - name: old
          in: query
          required: true
          type: string
        - name: plain
          in: query
          required: true
          type: string
        - name: verify
          in: query
          required: true
          type: string
      tags:
        - crx
  /crx/packmgr/service.jsp:
    post:
      operationId: postPackageService
      parameters:
        - name: cmd
          in: query
          required: true
          type: string
      responses:
        default:
          schema:
            type: string
      tags:
        - crx
  /crx/packmgr/update.jsp:
    post:
      operationId: postPackageUpdate
      parameters:
        - name: groupName
          in: query
          required: true
          type: string
        - name: packageName
          in: query
          required: true
          type: string
        - name: version
          in: query
          required: true
          type: string
        - name: path
          in: query
          required: true
          type: string
        - name: _charset_
          in: query
          required: false
          type: string
      tags:
        - crx
  # /crx/packmgr/service/.json/:
  /crx/packmgr/service/.json/etc/packages/{name}:
    post:
      operationId: postPackageServiceJson
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: cmd
          in: query
          required: true
          type: string
        - name: groupName
          in: query
          required: false
          type: string
        - name: packageName
          in: query
          required: false
          type: string
        - name: packageVersion
          in: query
          required: false
          type: string
        - name: _charset_
          in: query
          required: false
          type: string
      tags:
        - crx
  /system/console/bundles/{name}:
    post:
      operationId: postBundle
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: action
          in: query
          required: true
          type: string
      tags:
        - console
  /system/console/jmx/com.adobe.granite:type=Repository/op/{action}:
    post:
      operationId: postJmxRepository
      parameters:
        - name: action
          in: path
          required: true
          type: string
      tags:
        - console
